name: Replace contents of files

on:
  push:

jobs:
  replace_template_content:
  
    runs-on: ubuntu-latest
    if: github.run_number == 1

    steps:
      - uses: actions/checkout@v2

      - name: Replace template contents
        shell: pwsh
        run: |
          $repoName = ./.github/scripts/GetProjectName.ps1 -Repository ${{ github.repository }}
          Write-Output "Repo name is $repoName"
          $nuspecFile = Get-Item -Path ./UXAV.DeviceTemplate/UXAV.DeviceTemplate.nuspec
          (Get-Content $nuspecFile) -replace 'uxav/DeviceTemplate', '${{ github.repository }}' | Set-Content $nuspecFile
          ./.github/scripts/ReplaceContents.ps1 -Path ./ -Search DeviceTemplate -Replacement $repoName
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7.1.0
        with:
          message: Contents replaced by GitHub Actions on first run
          push: true
